name: Build & Push Core

on:
  workflow_run:
    workflows: "Create Release"
    branches: main
    types: completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        run: |
          CONTENT=fromJson($(jq -r 'tostring' 05-matrix/github_action_matrix_all.json))
          BAKE_JSON=04-bakefiles/${{ CONTENT.r_version }}.docker-bake.json
          for itarget in $(jq '.group[].${{ CONTENT.group }}[].targets[]' -r ${BAKE_JSON}); do
            docker buildx bake \
              --file ${BAKE_JSON} \
              --set=*.labels.org.opencontainers.image.revision=${GITHUB_SHA} \
              --push ${itarget};
          done
