name: Build & Push Devel

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composefile: [devel.yml]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker images
        run: docker-compose -f 03-compose/${{ matrix.composefile }} build
      - name: Push Docker images
        run: docker-compose -f 03-compose/${{ matrix.composefile }} push
