# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: main
    paths: 
      - "README.Rmd"
      - "01-stacks/devel.json"
  workflow_dispatch:


name: Render README

jobs:
  render-readme:
    runs-on: macOS-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown, data.table, and here
        run: |
          Rscript -e 'utils::install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'
          Rscript -e 'pak::pkg_install(c("rmarkdown", "jsonlite", "here"))'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_options = list(html_preview = FALSE))'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
