name: Create New Release

on:
  push:
    branches: main
    paths: "05-matrix/github_action_matrix_all.json"
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version from date
        id: get_version
        run: |
          NEW_VERSION=$(date '+v%Y.%m')
          echo ::set-output name=newversion::${NEW_VERSION}
          echo ${NEW_VERSION}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          tag_prefix: ${{ steps.get_version.outputs.newversion }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
