name: Create CORE-Release

on:
  push:
    branches: main
    paths:
      - "05-matrix/github_action_matrix_all.json"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  core-release:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/core-release.yml
        secrets: inherit
        with:
          tag_prefix: "R"
