name: Create New Release

on:
  push:
    branches: main
    paths: "05-matrix/github_action_matrix_all.json"
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate release tag
        uses: amitsingh-007/next-release-tag@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
