name: Create New R Release

on:
  push:
    branches: main
    paths: "05-matrix/github_action_matrix_all.json"

jobs:
  create_r_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set R version from 05-matrix/github_action_matrix_all.json
        id: get_r_version
        run: |
          NEW_R_VERSION=$(jq '.r_version[-1]' -r 05-matrix/github_action_matrix_all.json)
          echo ::set-output name=newrversion::${NEW_R_VERSION}
          echo ${NEW_R_VERSION}
      - name: Bump R version and push R tag
        id: tag_r_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_tag: ${{ steps.get_r_version.outputs.newrversion }}
          tag_prefix: "R"
      - name: Create R Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_r_version.outputs.new_tag }}
          name: Release ${{ steps.tag_r_version.outputs.new_tag }}
          generateReleaseNotes: true
          allowUpdates: false
          token: ${{ secrets.GITHUB_TOKEN }}
