name: Build & Push Servers

on:
  workflow_run:
    workflows: "Build & Push UMR"
    branches: main
    types: completed
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-json
        run: |
          JSON=05-matrix/github_action_matrix_all_server.json
          echo ::set-output name=json::"${JSON}"
          echo "${JSON}"
      - id: set-matrix
        run: |
          CONTENT=$(jq -r 'tostring' ${{ steps.set-json.outputs.json }})
          echo ::set-output name=matrix::"${CONTENT}"
          echo "${CONTENT}"

  build:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker images
        run: |
          BAKE_JSON=04-bakefiles/${{ matrix.r_version }}.docker-bake.json
          for itarget in $(jq '.group[].${{ matrix.group }}[].targets[]' -r ${BAKE_JSON}); do docker buildx bake --file ${BAKE_JSON} --set=*.labels.org.opencontainers.image.revision=${GITHUB_SHA} --push ${itarget}; done
