name: Write Config Files

on:
  push:
    branches: main
    paths:
      - "01-stacks/devel.json"
      - "build/**"
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install pak
        run: Rscript -e 'utils::install.packages("pak", repos = sprintf("https://r-lib.github.io/p/pak/stable/%s/%s/%s", .Platform$pkgType, R.Version()$os, R.Version()$arch))'

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev distro-info-data
          Rscript -e 'pak::pkg_install(c("rversions", "data.table", "httr2", "jsonlite", "yaml"))'

      - name: Make changes to pull request
        run: |
          rm -rf 02-dockerfiles 03-compose 04-bakefiles
          Rscript ./build/build.R

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Automatic update of container definition files
          signoff: false
          branch: auto-detected-updates
          delete-branch: true
          title: "Automatic update of container definition files"
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
