name: Weekly Actions

on:
  schedule:
    - cron: "0 12 * * SUN"
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-devel:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        composefile: [devel.yml]
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install distro-info-data
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::rversions
            any::jsonlite
            any::httr2
            any::yaml
            any::data.table
      - name: Make changes to pull request
        run: |
          rm -rf 02-dockerfiles 03-compose 04-bakefiles
          Rscript ./build/build.R ${GITHUB_REPOSITORY_OWNER} bullseye
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker images
        run: docker-compose -f 03-compose/${{ matrix.composefile }} build
      - name: Push Docker images
        run: docker-compose -f 03-compose/${{ matrix.composefile }} push
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Automatic update of container definition files
          signoff: false
          branch: auto-detected-updates
          delete-branch: true
          title: "Automatic update of container definition files"
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
